[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared", default-features = false }

leptos = { version = "0.8.15", features = ["csr"] }
web-sys = { version = "0.3", features = ["Window", "Storage"] }

serde_json = "1.0"

gloo-net = "0.6.0"
gloo-timers = { version = "0.3.0", features = ["futures"] }
console_error_panic_hook = "0.1.7"
futures = "0.3.31"
wasm-bindgen-futures = "0.4.56"